# Generated by Django 5.2.1 on 2025-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
