# Generated by Django 5.2.1 on 2025-11-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_user_registration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Registration',
        ),
    ]
