# Generated by Django 5.2.8 on 2025-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailaddress', models.EmailField(max_length=60)),
                ('contactnumber', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=25)),
                ('achievements', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=15)),
                ('profileimg', models.ImageField(default=True, upload_to='doc')),
                ('certificate', models.ImageField(default=True, upload_to='doc')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
