# Generated by Django 5.2.8 on 2025-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_registration',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
