# Generated by Django 5.2.8 on 2025-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_registration',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
