# Generated by Django 5.2.8 on 2025-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_registration_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_registration',
            name='adminapprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer_registration',
            name='adminreject',
            field=models.BooleanField(default=False),
        ),
    ]
