# Generated by Django 5.2.8 on 2025-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_trainer_registration_adminapprove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_registration',
            name='certificate',
            field=models.ImageField(default=True, upload_to='doc_certificate'),
        ),
        migrations.AlterField(
            model_name='trainer_registration',
            name='profileimg',
            field=models.ImageField(default=True, upload_to='doc_profileimg'),
        ),
    ]
