# Generated by Django 5.2.8 on 2025-12-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainer_registration_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Add_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=10)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer_registration')),
            ],
        ),
    ]
