# Generated by Django 5.2.8 on 2025-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_trainer_add_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_registration',
            name='specification',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
