# Generated by Django 5.2.8 on 2025-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_trainer_registration_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_registration',
            name='specification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
