# Generated by Django 5.2.8 on 2026-01-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_trainer_registration_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_registration',
            name='Expected_income',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
