# Generated by Django 5.2.8 on 2025-11-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
