# Generated by Django 5.2.8 on 2025-12-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0002_gymproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymproduct',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
