# Generated by Django 5.2.8 on 2025-12-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0003_alter_gymproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymproduct',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gymproduct',
            name='stock',
            field=models.CharField(max_length=20),
        ),
    ]
