# Generated by Django 5.2.8 on 2025-12-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_trainer_add_slot'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=30)),
                ('is_booked', models.BooleanField(default=False)),
                ('paystatus', models.BooleanField(default=False)),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer_registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
    ]
