# Generated by Django 5.2.8 on 2025-12-30 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_trainer_add_slot'),
        ('user', '0002_trainer_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_booking',
            name='slot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer_add_slot'),
        ),
    ]
