# Generated by Django 5.2.8 on 2026-01-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_trainer_booking_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_booking',
            name='Conf_Time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer_booking',
            name='slot',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
