# Generated by Django 5.2.8 on 2026-01-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_trainer_booking_conf_time_alter_trainer_booking_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_booking',
            old_name='Conf_Time',
            new_name='Expected_income',
        ),
    ]
