# Generated by Django 5.2.8 on 2026-01-01 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_conf_time_trainer_booking_expected_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_booking',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
