# Generated by Django 5.2.8 on 2026-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_trainer_booking_booked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_booking',
            name='suggestions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainer_booking',
            name='workout',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
