# Generated by Django 5.2.8 on 2026-01-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_trainer_booking_suggestions_trainer_booking_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_booking',
            old_name='suggestions',
            new_name='health_issues',
        ),
        migrations.RenameField(
            model_name='trainer_booking',
            old_name='workout',
            new_name='notes',
        ),
    ]
