# Generated by Django 5.2.8 on 2026-01-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_suggestions_trainer_booking_health_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='age',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='userprofile/'),
        ),
    ]
