# Generated by Django 5.2.8 on 2026-01-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_registration_age_user_registration_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
