# Generated by Django 5.2.8 on 2026-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_registration_allergies_user_registration_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_booking',
            name='Goal',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
