# Generated by Django 5.2.8 on 2026-01-06 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0004_alter_gymproduct_description_alter_gymproduct_stock'),
        ('user', '0011_trainer_booking_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_status', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nadmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newadmin.newadmin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newadmin.gymproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
    ]
