# Generated by Django 5.2.8 on 2026-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_product_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_booking',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_booking',
            name='pname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product_booking',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
